### ISSUE TITLE
quantity gem conflicts with ActiveSupport

### ISSUE THREAD

**Issue by mtodd** [johnewart/ruby-metrics#18]
The following snippet causes an error when ActiveSupport is loaded (like in a Rails app):

``` ruby
@rescale_window = 1.hour.to_seconds.to_i
```

This is due to `1.hour` returning a duration instead of the expected object from the `quantity` gem.

See this Gist for backtrace:
https://gist.github.com/943961

Should we look into patching the `quantity` gem to then patch ActiveSupport to support its methods?

**Comment by mtodd** [comment]
Playing with this now to see what can mitigate/fix this.

**Comment by mtodd** [comment]
See:
https://github.com/bhuga/quantity/issues/2

**Comment by mtodd** [comment]
Now includes pull request to make it work.

I'm not sure that the gem is actively being maintained. Many of the specs fail and the last commits were from quite some time ago (over a year ago).

I brought this up before, but perhaps we could do without this dependency? Our option would be to specify interesting constants ourselves or use ActiveSupport's Durations and time extensions to Numeric. It's not necessarily better, but it should give us the ease and functionality needed while broadening the compatible user base (read: Rails users).

The homegrown option could be nice since dependence on ActiveSupport may mean we only support specific versions of Rails apps, or turn off other users from integrating it because of that dependency. (That's silly, but a concern.)

Thoughts?

Also, I'm curious why we need the nano scale at all? It's not obvious to me, but I haven't given it too much consideration either, so that doesn't surprise me. Just wondering what the reasoning is.

**Comment by mtodd** [comment]
Hey look, bhuga/quantity pulled in the updates and pushed up the new gem. This should fix the conflicts with `ActiveSupport`. See version 0.1.2.

The maintainer said that it wasn't necessarily abandoned, but that it was not under active development since the project it was written for is now defunct.

There are failing specs and outstanding concerns, but that shouldn't affect us (yet). However, maybe it's a good impetus to look into other options or roll our own conversions if they're needed at all.

**Comment by johnewart** [comment]
The nanosecond scale is because it's the smallest time interval .. I think it's probably simplest to just remove this and do the math ourselves since it's not like we need any crazy conversions :D I ran into this when I added metrics to a project that had ActiveSupport loaded and just fixed it.

**Comment by mtodd** [comment]
What was the fix you applied?

I agree, would be good to remove and simplify. Gets rid of a dependency! :)

Anything I can help with?

**Comment by eric** [comment]
I've been holding off on integrating ruby-metrics until the ActiveSupport conflict is resolved. Is this something that is going to be released soon?

**Comment by johnewart** [comment]
Yep! It's been crazy the last week or so, I'll commit, push and release a new version of the gem tonight!

**Comment by mtodd** [comment]
The newest version of @bhuga's Quantity (0.1.2) has a requirable patch for ActiveSupport:

``` ruby
require 'ruby-metrics'
require 'quantity/rails'
```

See:
https://github.com/bhuga/quantity/commit/62794c302f1eb70de5aea5ae22d23342f4fc0a6a
https://github.com/bhuga/quantity/commit/f646f934d865ca1d69f9164b7db2b330195111fe

**Comment by mtodd** [comment]
But that's not figuring in @johnewart's changes that fix or remove Quantity internally.

**Comment by johnewart** [comment]
It may be worth re-integrating, but I had mostly phased it out anyway, it's really just a convenience thing and only used in one place in the library itself and in a spec test. Should be okay now as of 0.8.5

**Comment by eric** [comment]
Thanks!
