### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by nirvdrum** [johnewart/ruby-metrics#22]
It'd be extremely helpful if there were a changelog summarizing what's new in each release.

**Comment by johnewart** [comment]
Sure thing! I'll add one for the latest release.  

-John

**Comment by johnewart** [comment]
Done, I tried to be historically accurate but I'll definitely work to keep this up-to-date at each release.

**Comment by nirvdrum** [comment]
Very much appreciated.  Thanks for responding so quickly.
