### ISSUE TITLE
gem name

### ISSUE THREAD

**Issue by richardiux** [johnewart/ruby-metrics#8]
Hi Jhon,

Your project name is called `ruby-metrics`, but you are calling your libraries/directories `metrics`. I'm trying to bundle it into a gem, but let's clarify the gem name. I would suggest naming it `ruby-metrics`.

Please look at my fork
https://github.com/richardiux/ruby-metrics

Awesome work by the way.

**Comment by johnewart** [comment]
ruby-metrics sounds fine by me. I'll take a look at your pull request and then merge it!
